const GAME_ONE_MIN_WINNER_NUM = 1;
const GAME_ONE_MAX_TURN_NUM = 35;
const GAME_TWO_MAX_TURN_NUM = 9;
const ROOM_WAIT_TIME_MILLISECONDS = 20000;
const DEFAULT_PLAYER_LOCATION = 50;
const GAME_ONE_PAYOUT = 1;
const TOKEN_VALUE = 0.1;

module.exports = {
  GAME_ONE_MIN_WINNER_NUM: GAME_ONE_MIN_WINNER_NUM,
  GAME_ONE_MAX_TURN_NUM: GAME_ONE_MAX_TURN_NUM,
  GAME_TWO_MAX_TURN_NUM: GAME_TWO_MAX_TURN_NUM,
  ROOM_WAIT_TIME_MILLISECONDS: ROOM_WAIT_TIME_MILLISECONDS,
  DEFAULT_PLAYER_LOCATION: DEFAULT_PLAYER_LOCATION,
  GAME_ONE_PAYOUT: GAME_ONE_PAYOUT,
  TOKEN_VALUE: TOKEN_VALUE,
}