const GAME_ONE_MIN_WINNER_NUM = 1;
const GAME_ONE_MAX_ROUND_NUM = 20;
const GAME_TWO_MAX_ROUND_NUM = 20;
const ROOM_WAIT_TIME_MILLISECONDS = 20000;
const DEFAULT_PLAYER_LOCATION = 50;

module.exports = {
  GAME_ONE_MIN_WINNER_NUM: GAME_ONE_MIN_WINNER_NUM,
  GAME_ONE_MAX_ROUND_NUM: GAME_ONE_MAX_ROUND_NUM,
  GAME_TWO_MAX_ROUND_NUM: GAME_TWO_MAX_ROUND_NUM,
  ROOM_WAIT_TIME_MILLISECONDS: ROOM_WAIT_TIME_MILLISECONDS,
  DEFAULT_PLAYER_LOCATION: DEFAULT_PLAYER_LOCATION,
}